name: Testing

on:
  push:
    branches:
    - master

jobs:
  build:
    name: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: step1
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn install
